/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: ['class', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        // M3 Core Roles
        primary: {
          DEFAULT: 'var(--md-sys-color-primary)',
          container: 'var(--md-sys-color-primary-container)',
          fixed: 'var(--md-sys-color-primary-fixed)',
          'fixed-dim': 'var(--md-sys-color-primary-fixed-dim)',
        },
        'on-primary': 'var(--md-sys-color-on-primary)',
        'on-primary-container': 'var(--md-sys-color-on-primary-container)',
        'on-primary-fixed': 'var(--md-sys-color-on-primary-fixed)',
        'on-primary-fixed-variant': 'var(--md-sys-color-on-primary-fixed-variant)',

        secondary: {
          DEFAULT: 'var(--md-sys-color-secondary)',
          container: 'var(--md-sys-color-secondary-container)',
          fixed: 'var(--md-sys-color-secondary-fixed)',
          'fixed-dim': 'var(--md-sys-color-secondary-fixed-dim)',
        },
        'on-secondary': 'var(--md-sys-color-on-secondary)',
        'on-secondary-container': 'var(--md-sys-color-on-secondary-container)',
        'on-secondary-fixed': 'var(--md-sys-color-on-secondary-fixed)',
        'on-secondary-fixed-variant': 'var(--md-sys-color-on-secondary-fixed-variant)',

        tertiary: {
          DEFAULT: 'var(--md-sys-color-tertiary)',
          container: 'var(--md-sys-color-tertiary-container)',
          fixed: 'var(--md-sys-color-tertiary-fixed)',
          'fixed-dim': 'var(--md-sys-color-tertiary-fixed-dim)',
        },
        'on-tertiary': 'var(--md-sys-color-on-tertiary)',
        'on-tertiary-container': 'var(--md-sys-color-on-tertiary-container)',
        'on-tertiary-fixed': 'var(--md-sys-color-on-tertiary-fixed)',
        'on-tertiary-fixed-variant': 'var(--md-sys-color-on-tertiary-fixed-variant)',

        error: {
          DEFAULT: 'var(--md-sys-color-error)',
          container: 'var(--md-sys-color-error-container)',
        },
        'on-error': 'var(--md-sys-color-on-error)',
        'on-error-container': 'var(--md-sys-color-on-error-container)',

        surface: {
          DEFAULT: 'var(--md-sys-color-surface)',
          dim: 'var(--md-sys-color-surface-dim, #E2E8F0)',
          bright: 'var(--md-sys-color-surface-bright, #FFFFFF)',
          lowest: 'var(--md-sys-color-surface-container-lowest)',
          low: 'var(--md-sys-color-surface-container-low)',
          container: 'var(--md-sys-color-surface-container)',
          high: 'var(--md-sys-color-surface-container-high)',
          highest: 'var(--md-sys-color-surface-container-highest)',
          variant: 'var(--md-sys-color-surface-variant)',
        },
        'on-surface': 'var(--md-sys-color-on-surface)',
        'on-surface-variant': 'var(--md-sys-color-on-surface-variant)',
        'inverse-surface': 'var(--md-sys-color-inverse-surface)',
        'inverse-on-surface': 'var(--md-sys-color-inverse-on-surface)',
        'inverse-primary': 'var(--md-sys-color-inverse-primary)',

        outline: 'var(--md-sys-color-outline)',
        'outline-variant': 'var(--md-sys-color-outline-variant)',
        'surface-tint': 'var(--md-sys-color-surface-tint)',

        // Semantic Data Roles (Charts & Price Comparisons)
        data: {
          lowest: 'var(--md-sys-color-data-lowest)',
          'on-lowest': 'var(--md-sys-color-on-data-lowest)',
          'lowest-container': 'var(--md-sys-color-data-lowest-container)',
          'on-lowest-container': 'var(--md-sys-color-on-data-lowest-container)',
          highest: 'var(--md-sys-color-data-highest)',
          'on-highest': 'var(--md-sys-color-on-data-highest)',
          'highest-container': 'var(--md-sys-color-data-highest-container)',
          'on-highest-container': 'var(--md-sys-color-on-data-highest-container)',
          neutral: 'var(--md-sys-color-data-neutral)',
          'on-neutral': 'var(--md-sys-color-on-data-neutral)',
          'neutral-container': 'var(--md-sys-color-data-neutral-container)',
          'on-neutral-container': 'var(--md-sys-color-on-data-neutral-container)',
          positive: 'var(--md-sys-color-data-positive)',
          negative: 'var(--md-sys-color-data-negative)',
          series1: 'var(--md-sys-color-data-series-1)',
          series2: 'var(--md-sys-color-data-series-2)',
          series3: 'var(--md-sys-color-data-series-3)',
          series4: 'var(--md-sys-color-data-series-4)',
          series5: 'var(--md-sys-color-data-series-5)',
          series6: 'var(--md-sys-color-data-series-6)',
          series7: 'var(--md-sys-color-data-series-7)',
          series8: 'var(--md-sys-color-data-series-8)',
        },
      },
      fontFamily: {
        sans: ['"Roboto Flex"', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'Roboto', 'sans-serif'],
        display: ['"Roboto Flex"', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      borderRadius: {
        'none': 'var(--md-sys-shape-none)',
        'xs': 'var(--md-sys-shape-extra-small)',
        'sm': 'var(--md-sys-shape-small)',
        'md': 'var(--md-sys-shape-medium)',
        'lg': 'var(--md-sys-shape-large)',
        'xl': 'var(--md-sys-shape-extra-large)',
        '2xl': 'var(--md-sys-shape-extra-large-increased)',
        '3xl': 'var(--md-sys-shape-extra-extra-large)',
        'pill': 'var(--md-sys-shape-pill)',
      },
      boxShadow: {
        'elevation-0': 'var(--md-sys-elevation-0)',
        'elevation-1': 'var(--md-sys-elevation-1)',
        'elevation-2': 'var(--md-sys-elevation-2)',
        'elevation-3': 'var(--md-sys-elevation-3)',
        'elevation-4': 'var(--md-sys-elevation-4)',
        'elevation-5': 'var(--md-sys-elevation-5)',
      },
      spacing: {
        'card-p': 'var(--md-sys-spacing-card-padding)',
        'card-gap': 'var(--md-sys-spacing-card-gap)',
        'screen-m': 'var(--md-sys-spacing-screen-margin)',
      },
      transitionDuration: {
        'spatial-fast': 'var(--spring-duration-spatial-fast)',
        'spatial-default': 'var(--spring-duration-spatial-default)',
        'spatial-slow': 'var(--spring-duration-spatial-slow)',
        'effects-fast': 'var(--spring-duration-effects-fast)',
        'effects-default': 'var(--spring-duration-effects-default)',
        'effects-slow': 'var(--spring-duration-effects-slow)',
      },
      transitionTimingFunction: {
        'spatial-fast': 'var(--spring-curve-spatial-fast, var(--spring-fallback-spatial-fast))',
        'spatial-default': 'var(--spring-curve-spatial-default, var(--spring-fallback-spatial-default))',
        'spatial-slow': 'var(--spring-curve-spatial-slow, var(--spring-fallback-spatial-slow))',
        'effects-fast': 'var(--spring-curve-effects-fast)',
        'effects-default': 'var(--spring-curve-effects-default)',
        'effects-slow': 'var(--spring-curve-effects-slow)',
      },
    },
  },
  plugins: [],
};
