/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#4f378a',
          container: '#EADDFF',
        },
        'on-primary': '#ffffff',
        'on-primary-container': '#21005D',
        secondary: {
          DEFAULT: '#016874',
          container: '#97F0FF',
        },
        'on-secondary': '#ffffff',
        'on-secondary-container': '#001F24',
        tertiary: {
          DEFAULT: '#7c0090',
          container: '#a200bc',
        },
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#fec7ff',
        error: {
          DEFAULT: '#B3261E',
          container: '#ffdad6',
        },
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        background: '#fbf9f6',
        'on-background': '#1C1B1F',
        surface: {
          DEFAULT: '#F3EDF7',
          dim: '#dbdad7',
          bright: '#fbf9f6',
          lowest: '#ffffff',
          low: '#f5f3f0',
          container: '#efeeeb',
          high: '#eae8e5',
          highest: '#e4e2df',
          variant: '#E7E0EC',
        },
        'on-surface': '#1D1B20',
        'on-surface-variant': '#494551',
        'inverse-surface': '#30312f',
        'inverse-on-surface': '#f2f0ed',
        outline: '#79747E',
        'outline-variant': '#cbc4d2',
        'surface-tint': '#6750a4',
        'primary-fixed': '#e9ddff',
        'primary-fixed-dim': '#cfbcff',
        'on-primary-fixed': '#22005d',
        'on-primary-fixed-variant': '#4f378a',
        'secondary-fixed': '#a2effd',
        'secondary-fixed-dim': '#85d2e0',
        'on-secondary-fixed': '#001f24',
        'on-secondary-fixed-variant': '#004f58',
        'tertiary-fixed': '#ffd6fe',
        'tertiary-fixed-dim': '#faabff',
        'on-tertiary-fixed': '#35003f',
        'on-tertiary-fixed-variant': '#7b008f',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'Inter', 'sans-serif'],
        display: ['Plus Jakarta Sans', 'Hanken Grotesk', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      borderRadius: {
        'sm': '0.25rem',
        'DEFAULT': '0.5rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
      },
    },
  },
  plugins: [],
};
